# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-31 11:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PhoneMsg',
            fields=[
                ('M_id', models.AutoField(primary_key=True, serialize=False)),
                ('M_name', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectList',
            fields=[
                ('P_id', models.AutoField(primary_key=True, serialize=False)),
                ('P_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('R_id', models.AutoField(primary_key=True, serialize=False)),
                ('R_name', models.CharField(max_length=20)),
                ('R_version', models.CharField(max_length=20)),
                ('R_context', models.CharField(max_length=100)),
                ('R_result', models.CharField(max_length=20)),
                ('R_note', models.CharField(max_length=50)),
                ('R_createtime', models.CharField(max_length=30)),
                ('R_projectname', models.CharField(max_length=20)),
                ('R_ower', models.CharField(max_length=20)),
                ('R_kexuan', models.CharField(max_length=20)),
            ],
        ),
    ]
