# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-31 12:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rc_test', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhoneDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=10)),
                ('sdk', models.CharField(max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='phonemsg',
            name='projectlist',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ProjectList', to='rc_test.ProjectList'),
        ),
        migrations.AddField(
            model_name='phonemsg',
            name='result',
            field=models.ManyToManyField(to='rc_test.Result'),
        ),
        migrations.AlterField(
            model_name='result',
            name='R_createtime',
            field=models.DateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u65f6\u95f4'),
        ),
        migrations.AddField(
            model_name='phonedetail',
            name='M_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='rc_test.PhoneMsg'),
        ),
    ]
