# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-07 04:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rc_test', '0002_auto_20180131_1223'),
    ]

    operations = [
        # migrations.AddField(
        #     model_name='result',
        #     name='R_ower',
        #     field=models.CharField(default='', max_length=20),
        # ),
        # migrations.AddField(
        #     model_name='result',
        #     name='R_projectname',
        #     field=models.CharField(default='', max_length=20),
        # ),
    ]
