# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-07 07:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rc_test', '0003_auto_20180307_1248'),
    ]

    operations = [
        # migrations.AddField(
        #     model_name='result',
        #     name='R_kexuan',
        #     field=models.CharField(default='', max_length=20),
        # ),
        # migrations.AlterField(
        #     model_name='result',
        #     name='R_ower',
        #     field=models.CharField(max_length=20),
        # ),
    ]
