# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-07 08:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rc_test', '0005_auto_20180307_1615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='result',
            name='R_kexuan',
            field=models.CharField(max_length=20),
        ),
    ]
